import { StyleSheet } from 'react-native'

export const theme = {
  color: {
    bg: '#0B0B0F',
    surface: '#15151C',
    surfaceAlt: '#1E1E28',
    line: '#2A2A38',
    ink: '#F5F5F7',
    muted: '#8E8EA0',
    dim: '#5A5A70',
    pro: '#2D7BFF',
    proInk: '#FFFFFF',
    con: '#FF2D87',
    conInk: '#0B0B0F',
    accent: '#C6FF3D',
    warn: '#FFB800',
    live: '#FF2D87',
    danger: '#C53A6C',
    dangerSurface: '#341623',
    overlay: 'rgba(11,11,15,0.72)',
    overlaySoft: 'rgba(11,11,15,0.55)',
  },
  radius: { sm: 8, md: 14, lg: 22, xl: 32, pill: 9999 },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, '2xl': 24, '3xl': 32 },
  font: {
    display: 'SpaceGrotesk_400Regular',
    displayMedium: 'SpaceGrotesk_500Medium',
    displaySemibold: 'SpaceGrotesk_600SemiBold',
    displayBold: 'SpaceGrotesk_700Bold',
    body: 'SpaceGrotesk_400Regular',
    bodyMedium: 'SpaceGrotesk_500Medium',
    bodySemibold: 'SpaceGrotesk_600SemiBold',
    bodyBold: 'SpaceGrotesk_700Bold',
    mono: 'JetBrainsMono_400Regular',
    monoMedium: 'JetBrainsMono_500Medium',
    monoBold: 'JetBrainsMono_700Bold',
  },
  type: {
    displayXL: { size: 44, lineHeight: 44, letterSpacing: -1.5 },
    displayLG: { size: 36, lineHeight: 38, letterSpacing: -1.2 },
    displayMD: { size: 26, lineHeight: 30, letterSpacing: -0.5 },
    titleLG: { size: 22, lineHeight: 26, letterSpacing: -0.4 },
    body: { size: 15, lineHeight: 22 },
    bodySM: { size: 13, lineHeight: 18 },
    label: { size: 11, lineHeight: 14, letterSpacing: 2 },
    tag: { size: 10, lineHeight: 14, letterSpacing: 1.5 },
  },
} as const

export const textStyles = StyleSheet.create({
  displayXL: {
    fontFamily: theme.font.displayBold,
    fontSize: theme.type.displayXL.size,
    lineHeight: theme.type.displayXL.lineHeight,
    letterSpacing: theme.type.displayXL.letterSpacing,
    color: theme.color.ink,
  },
  displayLG: {
    fontFamily: theme.font.displayBold,
    fontSize: theme.type.displayLG.size,
    lineHeight: theme.type.displayLG.lineHeight,
    letterSpacing: theme.type.displayLG.letterSpacing,
    color: theme.color.ink,
  },
  displayMD: {
    fontFamily: theme.font.displaySemibold,
    fontSize: theme.type.displayMD.size,
    lineHeight: theme.type.displayMD.lineHeight,
    letterSpacing: theme.type.displayMD.letterSpacing,
    color: theme.color.ink,
  },
  titleLG: {
    fontFamily: theme.font.displaySemibold,
    fontSize: theme.type.titleLG.size,
    lineHeight: theme.type.titleLG.lineHeight,
    letterSpacing: theme.type.titleLG.letterSpacing,
    color: theme.color.ink,
  },
  body: {
    fontFamily: theme.font.body,
    fontSize: theme.type.body.size,
    lineHeight: theme.type.body.lineHeight,
    color: theme.color.ink,
  },
  bodySM: {
    fontFamily: theme.font.body,
    fontSize: theme.type.bodySM.size,
    lineHeight: theme.type.bodySM.lineHeight,
    color: theme.color.muted,
  },
  bodySemibold: {
    fontFamily: theme.font.bodySemibold,
    fontSize: theme.type.body.size,
    lineHeight: theme.type.body.lineHeight,
    color: theme.color.ink,
  },
  label: {
    fontFamily: theme.font.monoBold,
    fontSize: theme.type.label.size,
    lineHeight: theme.type.label.lineHeight,
    letterSpacing: theme.type.label.letterSpacing,
    color: theme.color.muted,
    textTransform: 'uppercase',
  },
  tag: {
    fontFamily: theme.font.monoBold,
    fontSize: theme.type.tag.size,
    lineHeight: theme.type.tag.lineHeight,
    letterSpacing: theme.type.tag.letterSpacing,
    color: theme.color.muted,
    textTransform: 'uppercase',
  },
})
